datadog:
  apiKeyExistingSecret: datadog-agent
  # Disable kubelet TLS Verification in minikube
  kubelet:
    tlsVerify: false
  kubeStateMetricsCore:
    enabled: true
  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    instrumentation:
      enabled: true
      libVersions:
        dotnet: "3"
        python: "2"
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager
    - kube_scheduler
