apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      initContainers:
      - name: copy-index-html
        image: busybox:latest
        command: ["sh", "-c", "cp /data/index.html /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: html-files
          mountPath: /data
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-files
        hostPath:
          path: /Users/daniel.croft/Documents/git/minikube/index.html  # Replace with the absolute path to your index.html
          type: File
      - name: nginx-html
        emptyDir: {}

